version: "3"
services:
  nodejs:
    build: .
    container_name: navi-nodejs
    volumes:
      - .:/app/:rw
    command: "npm run build"
    ports:
      - "8086:8086"
    restart: always
    networks:
      - default

  nginx:
    image: nginx:stable-alpine
    container_name: navi-nginx
    ports:
      - "8087:80"
    volumes:
      - ./dist:/usr/share/nginx/html/:rw
    restart: always
    networks:
      - default

networks:
  default: