version: "3"
services:
  nodejs:
    build: .
    container_name: navi-nodejs
    volumes:
      - .:/project/:rw
    command: "npm run-script build && npm run build"
    networks:
      - default

  nginx:
    image: nginx:stable-alpine
    container_name: navi-nginx
    ports:
      - "8083:80"
    volumes:
      - ./dist:/usr/share/nginx/html/:rw
    restart: always
    networks:
      - default

networks:
  default: