version: "3"
services:
  nodejs:
    build: .
    volumes:
      - .:/project/:rw
    working_dir: /project
    command: "npm run-script build"
    networks:
      - default

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8086:80"
    volumes:
      - ./dist:/usr/share/nginx/html/:rw
    restart: always
    networks:
      - default

networks:
  default: